// <auto-generated />
namespace Event_Attendees_Tracker_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CreatingMaster_DBROlesTablewithmappingdbrolesanduserdetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatingMaster_DBROlesTablewithmappingdbrolesanduserdetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202003051003230_Creating Master_DBROles Table with mapping dbroles and userdetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
